extends Node2D

const CENTER := Vector2(480.0, 270.0)
const TARGET_RADIUS := 18.0
const AGENT_RADIUS := 14.0

var controller: PIDControllerNode
var target := CENTER
var agent := CENTER + Vector2(-220.0, 120.0)
var velocity := Vector2.ZERO
var elapsed := 0.0
var paused := false
var status_label: Label

func _ready() -> void:
	controller = PIDControllerNode.new()
	add_child(controller)
	controller.set_kp(2.0)
	controller.set_ki(0.15)
	controller.set_kd(0.35)
	controller.set_limits(-900.0, 900.0)

	status_label = Label.new()
	status_label.position = Vector2(24.0, 20.0)
	status_label.add_theme_font_size_override("font_size", 18)
	add_child(status_label)
	_update_status()
	queue_redraw()

func _process(delta: float) -> void:
	if paused:
		return

	elapsed += delta
	# The target follows a path generated by the Godot simulation.
	target = CENTER + Vector2(
		sin(elapsed * 0.9) * 280.0,
		cos(elapsed * 1.3) * 140.0
	)

	# The PID controller produces acceleration for the simulated agent.
	var control_x := controller.update_dt(target.x, agent.x, delta)
	var control_y := controller.update_dt(target.y, agent.y, delta)
	velocity += Vector2(control_x, control_y) * delta
	velocity = velocity.limit_length(420.0)
	agent += velocity * delta

	_update_status()
	queue_redraw()

func _unhandled_input(event: InputEvent) -> void:
	if event is InputEventKey and event.pressed and not event.echo:
		if event.keycode == KEY_SPACE:
			paused = not paused
		if event.keycode == KEY_R:
			agent = CENTER + Vector2(-220.0, 120.0)
			velocity = Vector2.ZERO
			controller.reset()

func _update_status() -> void:
	if status_label == null:
		return
	var distance := agent.distance_to(target)
	status_label.text = "PID Target Tracking\n" + \
		"The controller drives the blue agent toward the moving target.\n" + \
		"Distance: %.1f    SPACE: pause    R: reset" % distance

func _draw() -> void:
	draw_rect(Rect2(Vector2.ZERO, Vector2(960.0, 540.0)), Color("101827"))
	# Draw a faint path grid to make the movement visible.
	for x in range(0, 961, 48):
		draw_line(Vector2(x, 0), Vector2(x, 540), Color("1b2a40"), 1.0)
	for y in range(0, 541, 48):
		draw_line(Vector2(0, y), Vector2(960, y), Color("1b2a40"), 1.0)

	draw_line(agent, target, Color("496a91"), 2.0)
	draw_circle(target, TARGET_RADIUS, Color("ef6a6a"))
	draw_circle(agent, AGENT_RADIUS, Color("62b0ff"))
	draw_circle(agent, AGENT_RADIUS + 6.0, Color("62b0ff", 0.25), false, 2.0)
