#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

# Append the include path for the 'src' directory and Eigen library
env.Append(CPPPATH=["src/", "C:/libs/eigen-3.4.0"])

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# Point and link all of the node libraries
sources = (Glob("src/*.cpp") + Glob("src/neural_network/*.cpp") + Glob("src/replay_buffer/*.cpp")
           + Glob("src/test_network_node/*.cpp") + Glob("src/layer/*.cpp"))

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "bin/mlgodotkit.{}.{}.framework/libmlgodotkit.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
elif env["platform"] == "ios":
    if env["ios_simulator"]:
        library = env.StaticLibrary(
            "bin/mlgodotkit.{}.{}.simulator.a".format(env["platform"], env["target"]),
            source=sources,
        )
    else:
        library = env.StaticLibrary(
            "bin/mlgodotkit.{}.{}.a".format(env["platform"], env["target"]),
            source=sources,
        )
else:
    library = env.SharedLibrary(
        "bin/mlgodotkit{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
