name: Release MLGodotKit

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Collect build files
        run: |
          mkdir release
          cp mlgodotkit/bin/*.dll release/
          cp mlgodotkit/bin/*.a release/
          cp mlgodotkit/mlgodotkit.gdextension release/
          cd release
          zip -r ../mlgodotkit.zip .

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: ./mlgodotkit.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT}}
